name: project
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0-102.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  mobx: ^2.1.4
  flutter_mobx: ^2.0.6+5
  firebase_core: ^2.11.0
  shared_preferences: ^2.1.0
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.6.1
  cloud_firestore: ^4.7.1
  google_sign_in: ^5.4.4
  quill_html_editor: ^2.1.9
  provider: ^6.0.5
  file_picker: '5.2.6'
  html: ^0.15.3
  equatable: ^2.0.5
  sqflite: ^2.2.8+3
  path: ^1.8.3
  uuid: ^3.0.7
  google_mobile_ads: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  mobx_codegen: ^2.2.0
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/icons/
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-VariableFont_wght.ttf
    - family: MontserratMedium
      fonts:
        - asset: assets/fonts/Montserrat-Medium.ttf
    - family: PlayFair
      fonts:
        - asset: assets/fonts/PlayfairDisplay-VariableFont_wght.ttf
